Repository GSG-G13/Borrow-Book, pull requests merged in 2023-04, with the labels that each got.

#1 add file structure
  .gitignore
  package-lock.json
  package.json
  public/errors/404.html
  public/errors/500.html
  public/index.html
  public/scripts/script.js
  public/styles/style.css
  src/app.js
  src/controllers/index.js
  src/database/config/build.sql
  src/database/config/connection.js
  src/database/queries/index.js
  src/index.js
  src/router/index.js
Labels: awaiting

#10 server the public file
  src/app.js
Labels: done

#12 build-database-file
  src/database/config/build.sql
  src/database/config/connection.js
  src/database/queries/addBook.js
  src/database/queries/addUser.js
Labels: awaiting

#23 make a sginup function work
  public/scripts/dom.js
  src/controllers/sginup/sginup.js
  src/database/config/build.sql
  src/database/queries/addUser.js
  src/router/index.js
  src/utiles/validation/signupSchema.js
Labels: done

#28 edit dom
  .vscode/settings.json
  public/pages/books.html
  public/pages/profile.html
  public/scripts/dist/dom.dev.js
  public/scripts/dom.js
  src/controllers/index.js
Labels: awaiting

#37 create-readme-file
  README.md
  src/controllers/dist/deleteBook.dev.js
Labels: awaiting, done

#41 create test db
  .vscode/settings.json
  package-lock.json
  package.json
  test/addBookSchema.js
  test/connction.test.js
  test/query.test/addBook.test.js
  test/query.test/addUser.test.js
  test/query.test/checkBookStatus.test.js
  test/query.test/deleteBookQuery.test.js
Labels: awaiting
